- name: restart hornet
  systemd:
    name: hornet.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  when:
    - not skip_hornet_restart|default(False)|bool
    - hornet_started is not defined or not hornet_started.changed
