- name: start hornet
  systemd:
    name: hornet.service
    state: started
    daemon_reload: yes
    enabled: yes
  register: hornet_started

- name: restart hornet
  systemd:
    name: hornet.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  when:
    - not skip_hornet_restart|default(False)|bool
    - not hornet_started.changed
